apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    receivers:
    - name: wechat
      wechat_configs:
      - agent_id: "100000x"
        api_secret: Nm7PRrxxxxG8EpkyWuXDAWMLmFo
        corp_id: wwf9d3833cd2323ewdd
        send_resolved: true
        to_user: Joker
    route:
      group_by:
      - job
      group_interval: 5m
      group_wait: 30s
      receiver: wechat
      repeat_interval: 12h
      routes:
      - match:
          alertname: Watchdog
        receiver: wechat
    templates:
    - /etc/alertmanager/config/template.tmp1
